### ISSUE TITLE
[Feature]: Make a link clickable

### ISSUE THREAD

**Issue by Asima-Das** [mindfiredigital/react-text-igniter#36]
### What problem does this feature solve?

Enter the below in the text area:

https://ourgoalplan.co.in/GoalSheet.aspx

Observe that the link is not clickable both in edit and preview mode.

![image](https://github.com/user-attachments/assets/8dbca534-10cf-432e-87bc-1ad73f8b3600)

**Comment by lakinmindfire** [comment]
NA
