### ISSUE TITLE
[BUG]:  Previous link remains in the "Add Link" modal when reopening for new link

### ISSUE THREAD

**Issue by geekychandan** [mindfiredigital/react-text-igniter#46]
### Describe the bug

When we try to add a new link by reopening the "Create Link" modal form, the modal still contains the previously entered link text and URL. The modal should reset its form fields (link text and URL) when it is reopened, so that the user can start with a fresh form.

### Steps to reproduce

1.Open the editor and click to create a link.
2.Enter a link text and URL in the modal and submit it.
3.Click to add another link and observe that the previous link’s data (text and URL) is still present in the modal fields.

### Expected behavior

When reopening the "Create Link" modal, the fields for link text and URL should be empty, allowing the user to input a new link.

### What is actually happening?

It is not Clearing the modal form fields when the modal is opened for a new link. Reseting the state  is needed.

**Comment by geekychandan** [comment]
Hello,
I would like to work on resolving this issue . Could you please assign it to me?
I’ll ensure the modal’s state is reset properly when reopening, and I’ll take care of ensuring the link styling and alignment don’t carry over to subsequent text.
Please let me know if there are any specific guidelines or requirements I should follow for this fix. Thank you!

**Comment by deepakyadav-01** [comment]
Hi @geekychandan , you can contribute by  forking the repo and raising pr against the issue will check code and merge , you have to follow certain coding guidelines , and code of conduct please read code_of_conduct.md and contributing.md for more information
